version: '3'
services:
  db:
    image: postgres:15.1
    container_name: pf_database
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./postgres:/var/lib/postgresql/data
  client:
    build: .
    image: front_next_pf
    ports:
      - 3010:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
    
  
